version: "3.9"
services:
  ingester:
    image: ingester
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/knox-dev-backend:/root/knox-dev-backend
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    working_dir: /app