version: "3.9"
services:
  ingester:
    image: ingester
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/knox-dev-backend:/root/knox-dev-backend
    env_file:
      - .env
    working_dir: /app